from django.contrib import admin

from .models import SelfemploymentIncomeSources, SelfemploymentExpenseSources, SelfemploymentDeductionSources, Months, SelfemploymentIncomesPerTaxYear, SelfemploymentExpensesPerTaxYear, SelfemploymentDeductionsPerTaxYear, SelfemploymentUkTaxConfigForTaxYear, SelfemploymentClass4TaxConfigForTaxYear, SelfemploymentClass2TaxConfigForTaxYear, TaxableIncomeSources, TaxableIncomeSourceForSubmission


admin.site.register([SelfemploymentIncomeSources, SelfemploymentExpenseSources, SelfemploymentDeductionSources, Months, SelfemploymentIncomesPerTaxYear, SelfemploymentExpensesPerTaxYear, SelfemploymentDeductionsPerTaxYear, SelfemploymentUkTaxConfigForTaxYear, SelfemploymentClass4TaxConfigForTaxYear, SelfemploymentClass2TaxConfigForTaxYear, TaxableIncomeSources, TaxableIncomeSourceForSubmission])
