# Generated by Django 3.2.3 on 2022-03-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='months',
            name='month_index',
            field=models.IntegerField(default=0, verbose_name='Index'),
        ),
    ]
