# Generated by Django 3.2.3 on 2022-03-08 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0041_auto_20220306_1820'),
        ('accounts', '0003_alter_months_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensespertaxyear',
            name='tax_year',
        ),
        migrations.RemoveField(
            model_name='incomespertaxyear',
            name='tax_year',
        ),
        migrations.AlterField(
            model_name='expensespertaxyear',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='companies.selfassesmentaccountsubmission'),
        ),
        migrations.AlterField(
            model_name='incomespertaxyear',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='companies.selfassesmentaccountsubmission'),
        ),
    ]
