# Generated by Django 3.2.3 on 2022-03-16 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_expensespertaxyear_expense_source'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='incomespertaxyear',
            constraint=models.UniqueConstraint(fields=('client', 'month', 'income_source'), name='unique record'),
        ),
    ]
