# Generated by Django 3.2.3 on 2022-03-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_incomespertaxyear_unique record'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='expensespertaxyear',
            constraint=models.UniqueConstraint(fields=('client', 'month', 'expense_source'), name='unique expense record'),
        ),
    ]
