# Generated by Django 3.2.9 on 2021-12-08 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedLoginAttempts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Public ip address of device')),
                ('credentials', models.TextField()),
                ('device_user_agent', models.TextField(verbose_name='User Agent')),
                ('tried_to_logged_in_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Failed User Login History',
                'verbose_name_plural': 'Failed User Login Histories',
            },
        ),
        migrations.CreateModel(
            name='UserLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Public ip address of device')),
                ('device_user_agent', models.TextField(verbose_name='User Agent')),
                ('logged_in_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Login History',
                'verbose_name_plural': 'User Login Histories',
            },
        ),
        migrations.CreateModel(
            name='ActiveUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_login_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_logs.userloginhistory')),
            ],
            options={
                'verbose_name': 'Active User',
                'verbose_name_plural': 'Active Users',
            },
        ),
    ]
