# Generated by Django 3.2.9 on 2021-12-08 05:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginhistory',
            name='logged_out_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
