# Generated by Django 5.1.4 on 2025-02-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_logs', '0003_failedloginattempts_extra_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failedloginattempts',
            name='credentials',
            field=models.TextField(default='', verbose_name='Login Credentials'),
        ),
        migrations.AlterField(
            model_name='failedloginattempts',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='Public IP'),
        ),
    ]
