# Generated by Django 3.2.9 on 2021-12-08 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_logs', '0004_alter_userloginhistory_logged_out_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='failedloginattempts',
            old_name='tried_to_logged_in_at',
            new_name='tried_to_log_in_at',
        ),
    ]
