# Generated by Django 3.1.7 on 2021-04-11 11:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Selfassesment',
            fields=[
                ('is_updated', models.BooleanField(default=True, editable=False, verbose_name='Update Status')),
                ('client_id', models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique ID for client')),
                ('client_file_number', models.IntegerField(null=True, unique=True, verbose_name='File Number')),
                ('client_name', models.CharField(db_index=True, max_length=100, verbose_name='Full Name')),
                ('client_phone_number', models.CharField(db_index=True, max_length=255, verbose_name='Phone numbers')),
                ('date_of_registration', models.DateField(default=django.utils.timezone.now, verbose_name='Registration date')),
                ('UTR', models.CharField(blank=True, db_index=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='Invalid UTR', message='Enter 10 digit UTR Number', regex=re.compile('^[0-9]{10}$'))], verbose_name='UTR')),
                ('HMRC_referance', models.TextField(blank=True, max_length=2048, null=True, verbose_name='HMRC')),
                ('NINO', models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(code='Invalid NINO', message='Enter 9 chars long NINO.', regex=re.compile('^(?!BG|GB|KN|NK|NT|TN|ZZ)[ABCEGHJKLMNOPRSTWXYZ][ABCEGHJKLMNPRSTWXYZ][0-9]{6}[ABCD]$', 2))], verbose_name='NINO')),
                ('gateway_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Gateway ID')),
                ('gateway_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Gateway Password')),
                ('address', models.TextField(blank=True, db_index=True, null=True, verbose_name='Address')),
                ('post_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Postal Code')),
                ('email', models.EmailField(blank=True, max_length=320, null=True, verbose_name='Email')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of Bank')),
                ('bank_account_number', models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(code='Invalid Bank Account', message='Enter 8 digit Bank Account Number', regex=re.compile('^[0-9]{8}$'))], verbose_name='Account number in Bank')),
                ('bank_sort_code', models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(code='Invalid Sort Code', message='Enter 6 digit Sort Code', regex=re.compile('^[0-9]{6}$'))], verbose_name='Bank Sort Code')),
                ('bank_account_holder_name', models.CharField(blank=True, max_length=100, verbose_name='Bank Account Holder Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utr_created_by', to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Selfassesment',
                'verbose_name_plural': 'Selfassesments',
            },
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('tracker_id', models.AutoField(db_index=True, primary_key=True, serialize=False, verbose_name='Tracker ID')),
                ('creation_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Tracker creation datetime')),
                ('job_description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('deadline', models.DateField(default=django.utils.timezone.now, verbose_name='Deadline')),
                ('complete_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Complete Date')),
                ('is_completed', models.BooleanField(blank=True, default=False, verbose_name='Status')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='companies.selfassesment', verbose_name='Client ID')),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tracker_created_by', to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='Created By')),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='done_by', to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='Done By')),
            ],
            options={
                'verbose_name': 'Tracker',
                'verbose_name_plural': 'Trackers',
            },
        ),
        migrations.CreateModel(
            name='SelfassesmentAccountSubmission',
            fields=[
                ('submission_id', models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False, verbose_name='Submission ID')),
                ('date_of_submission', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Submission date')),
                ('tax_year', models.CharField(blank=True, max_length=10, verbose_name='Tax Year')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('paid_amount', models.BigIntegerField(blank=True, null=True, verbose_name='Amount Paid')),
                ('is_paid', models.BooleanField(blank=True, default=False, verbose_name='Is Paid')),
                ('is_submitted', models.BooleanField(blank=True, default=False, verbose_name='Is Submitted')),
                ('account_prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_prepared_by', to=settings.AUTH_USER_MODEL, verbose_name='Prepared By')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.selfassesment', verbose_name='Client ID')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_by', to=settings.AUTH_USER_MODEL, verbose_name='Submitted By')),
            ],
            options={
                'verbose_name': 'Selfassesment Submission',
                'verbose_name_plural': 'Selfassesment Submissions',
            },
        ),
    ]
