# Generated by Django 3.2.2 on 2021-05-11 23:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Selfassesment',
            fields=[
                ('client_id', models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique ID for client')),
                ('date_of_registration', models.DateField(default=django.utils.timezone.now, verbose_name='Registration date')),
                ('is_updated', models.BooleanField(default=True, editable=False, verbose_name='Update Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('client_file_number', models.IntegerField(null=True, unique=True, verbose_name='File Number')),
                ('client_name', models.CharField(db_index=True, max_length=100, verbose_name='Full Name / Business Name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('PAYE_number', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='PAYE Number')),
                ('personal_phone_number', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Personal Phone numbers')),
                ('personal_email', models.EmailField(blank=True, max_length=320, null=True, verbose_name='Personal Email')),
                ('personal_address', models.TextField(blank=True, db_index=True, null=True, verbose_name='Personal Address')),
                ('personal_post_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Personal Postal Code')),
                ('gateway_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Personal Gateway ID')),
                ('gateway_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Gateway Password')),
                ('AOR_number', models.CharField(blank=True, db_index=True, max_length=511, null=True, verbose_name='Account Office Reference number')),
                ('business_phone_number', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Business Phone numbers')),
                ('business_email', models.EmailField(blank=True, max_length=320, null=True, verbose_name='Business Email')),
                ('business_address', models.TextField(blank=True, db_index=True, null=True, verbose_name='Business Address')),
                ('business_post_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Business Postal Code')),
                ('HMRC_referance', models.CharField(blank=True, max_length=1023, null=True, verbose_name='HMRC Referance')),
                ('UTR', models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid UTR', message='Enter 10 digit UTR Number', regex=re.compile('^[0-9]{10}$'))], verbose_name='UTR')),
                ('NINO', models.CharField(blank=True, max_length=9, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid NINO', message='Enter 9 chars long NINO.', regex=re.compile('^(?!BG|GB|KN|NK|NT|TN|ZZ)[ABCEGHJKLMNOPRSTWXYZ][ABCEGHJKLMNPRSTWXYZ][0-9]{6}[ABCD]$', 2))], verbose_name='NINO')),
                ('HMRC_agent', models.BooleanField(default=False, verbose_name='HMRC agent active status')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of Bank')),
                ('bank_account_number', models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(code='Invalid Bank Account', message='Enter 8 digit Bank Account Number', regex=re.compile('^[0-9]{8}$'))], verbose_name='Account number in Bank')),
                ('bank_sort_code', models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(code='Invalid Sort Code', message='Enter 6 digit Sort Code', regex=re.compile('^[0-9]{6}$'))], verbose_name='Bank Sort Code')),
                ('bank_account_holder_name', models.CharField(blank=True, max_length=100, verbose_name='Bank Account Holder Name')),
            ],
            options={
                'verbose_name': 'Selfassesment',
                'verbose_name_plural': 'Selfassesments',
            },
        ),
        migrations.CreateModel(
            name='SelfassesmentAccountSubmission',
            fields=[
                ('submission_id', models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False, verbose_name='Submission ID')),
                ('date_of_submission', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Submission date')),
                ('tax_year', models.CharField(blank=True, max_length=10, verbose_name='Tax Year')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('paid_amount', models.BigIntegerField(blank=True, null=True, verbose_name='Amount Paid')),
                ('is_paid', models.BooleanField(blank=True, default=False, verbose_name='Is Paid')),
                ('is_submitted', models.BooleanField(blank=True, default=False, verbose_name='Is Submitted')),
            ],
            options={
                'verbose_name': 'Selfassesment Submission',
                'verbose_name_plural': 'Selfassesment Submissions',
            },
        ),
        migrations.CreateModel(
            name='SelfassesmentType',
            fields=[
                ('type_id', models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Selfassesment Type Id')),
                ('type_name', models.CharField(db_index=True, default='New Selfassesment Type', max_length=255, verbose_name='Type Name')),
            ],
            options={
                'verbose_name': 'Selfassesment Type',
                'verbose_name_plural': 'Selfassesment Types',
            },
        ),
        migrations.CreateModel(
            name='SelfassesmentTracker',
            fields=[
                ('tracker_id', models.AutoField(db_index=True, primary_key=True, serialize=False, verbose_name='Tracker ID')),
                ('creation_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Tracker creation datetime')),
                ('job_description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('deadline', models.DateField(default=django.utils.timezone.now, verbose_name='Deadline')),
                ('is_completed', models.BooleanField(blank=True, default=False, verbose_name='Status')),
                ('complete_date', models.DateField(blank=True, null=True, verbose_name='Complete Date')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selfassesment_tracker_client_id', to='companies.selfassesment', verbose_name='Client ID')),
            ],
            options={
                'verbose_name': 'Selfassesment Tracker',
                'verbose_name_plural': 'Selfassesment Trackers',
            },
        ),
    ]
