# Generated by Django 3.1.7 on 2021-04-19 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Limited',
            fields=[
                ('client_id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='client_id')),
            ],
            options={
                'verbose_name': 'Limited',
                'verbose_name_plural': 'Limited Accounts',
            },
        ),
        migrations.CreateModel(
            name='LimitedTracker',
            fields=[
                ('tracker_id', models.AutoField(db_index=True, primary_key=True, serialize=False, verbose_name='Tracker ID')),
                ('creation_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Tracker creation datetime')),
                ('job_description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('deadline', models.DateField(default=django.utils.timezone.now, verbose_name='Deadline')),
                ('complete_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Complete Date')),
                ('is_completed', models.BooleanField(blank=True, default=False, verbose_name='Status')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limited_client_id', to='companies.limited', verbose_name='Client ID')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limited_tracker_created_by', to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='Created By')),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='limited_tracker_done_by', to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='Done By')),
            ],
            options={
                'verbose_name': 'Limited Tracker',
                'verbose_name_plural': 'Limited Trackers',
            },
        ),
        migrations.CreateModel(
            name='SelfassesmentTracker',
            fields=[
                ('tracker_id', models.AutoField(db_index=True, primary_key=True, serialize=False, verbose_name='Tracker ID')),
                ('creation_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Tracker creation datetime')),
                ('job_description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('deadline', models.DateField(default=django.utils.timezone.now, verbose_name='Deadline')),
                ('complete_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Complete Date')),
                ('is_completed', models.BooleanField(blank=True, default=False, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Selfassesment Tracker',
                'verbose_name_plural': 'Selfassesment Trackers',
            },
        ),
        migrations.AlterField(
            model_name='selfassesment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utr_created_by', to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='selfassesmentaccountsubmission',
            name='account_prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_prepared_by', to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='Prepared By'),
        ),
        migrations.AlterField(
            model_name='selfassesmentaccountsubmission',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_by', to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='Submitted By'),
        ),
        migrations.DeleteModel(
            name='Tracker',
        ),
        migrations.AddField(
            model_name='selfassesmenttracker',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='selfassesment_client_id', to='companies.selfassesment', verbose_name='Client ID'),
        ),
        migrations.AddField(
            model_name='selfassesmenttracker',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='selfassesment_tracker_created_by', to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='selfassesmenttracker',
            name='done_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='selfassesment_trackerdone_by', to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='Done By'),
        ),
    ]
