# Generated by Django 5.1.4 on 2025-01-01 04:40

import companies.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='limited',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limited_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='limitedconfirmationstatementtracker',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='limited_confirmation_client_id', to='companies.limited', verbose_name='Client ID'),
        ),
        migrations.AddField(
            model_name='limitedconfirmationstatementtracker',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='limited_confirmation_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By'),
        ),
        migrations.AddField(
            model_name='limitedonboardingtasks',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='limited_onboarding_tasks_client_id', to='companies.limited', verbose_name='Client ID'),
        ),
        migrations.AddField(
            model_name='limitedonboardingtasks',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='limited_onboarding_tasks_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='limitedonboardingtasks',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='limited_onboarding_tasks_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By'),
        ),
        migrations.AddField(
            model_name='limitedsubmissiondeadlinetracker',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='limited_account_submission_client_id', to='companies.limited', verbose_name='Client ID'),
        ),
        migrations.AddField(
            model_name='limitedsubmissiondeadlinetracker',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='limited_submission_submitted_by', to=settings.AUTH_USER_MODEL, verbose_name='Submitted By(CH)'),
        ),
        migrations.AddField(
            model_name='limitedsubmissiondeadlinetracker',
            name='submitted_by_hmrc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='limited_submission_submitted_by_hmrc', to=settings.AUTH_USER_MODEL, verbose_name='Submitted By(HM)'),
        ),
        migrations.AddField(
            model_name='limitedsubmissiondeadlinetracker',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='limited_submission_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By'),
        ),
        migrations.AddField(
            model_name='limitedtracker',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='limited_tracker_assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to'),
        ),
        migrations.AddField(
            model_name='limitedtracker',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='limited_tracker_client_id', to='companies.limited', verbose_name='Client ID'),
        ),
        migrations.AddField(
            model_name='limitedtracker',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='limited_tracker_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='limitedtracker',
            name='done_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limited_tracker_done_by', to=settings.AUTH_USER_MODEL, verbose_name='Done By'),
        ),
        migrations.AddField(
            model_name='limitedtracker',
            name='issue_created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limited_tracker_issue_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Issue Created By'),
        ),
        migrations.AddField(
            model_name='limitedvattracker',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='limited_vat_client_id', to='companies.limited', verbose_name='Client ID'),
        ),
        migrations.AddField(
            model_name='limitedvattracker',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='limited_vat_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By'),
        ),
        migrations.AddField(
            model_name='limitedonboardingtasks',
            name='task_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='limited_onboarding_tasks_task_id', to='companies.onboardingtask', verbose_name='Task ID'),
        ),
        migrations.AddField(
            model_name='selfassesment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selfassesment_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='autocreatedselfassesmenttracker',
            name='selfassesment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.selfassesment'),
        ),
        migrations.AddField(
            model_name='selfassesmentaccountsubmission',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='selfassesment_account_submission_assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to'),
        ),
        migrations.AddField(
            model_name='selfassesmentaccountsubmission',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selfassesment_account_submission_client_id', to='companies.selfassesment', verbose_name='Client ID'),
        ),
        migrations.AddField(
            model_name='selfassesmentaccountsubmission',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='selfassesment_account_submission_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By'),
        ),
        migrations.AddField(
            model_name='selfassesmentaccountsubmission',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selfassesment_account_submission_prepared_by', to=settings.AUTH_USER_MODEL, verbose_name='Prepared By'),
        ),
        migrations.AddField(
            model_name='selfassesmentaccountsubmission',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selfassesment_account_submission_submitted_by', to=settings.AUTH_USER_MODEL, verbose_name='Submitted By'),
        ),
        migrations.AddConstraint(
            model_name='selfassesmentaccountsubmissiontaxyear',
            constraint=models.UniqueConstraint(fields=('tax_year',), name='unique_tax_year'),
        ),
        migrations.AddField(
            model_name='selfassesmentaccountsubmission',
            name='tax_year',
            field=models.ForeignKey(default=companies.models.SelfassesmentAccountSubmissionTaxYear.get_max_year, null=True, on_delete=django.db.models.deletion.RESTRICT, to='companies.selfassesmentaccountsubmissiontaxyear'),
        ),
        migrations.AddField(
            model_name='selfassesmenttracker',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='selfassesment_tracker_assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to'),
        ),
        migrations.AddField(
            model_name='selfassesmenttracker',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selfassesment_tracker_client_id', to='companies.selfassesment', verbose_name='Client ID'),
        ),
        migrations.AddField(
            model_name='selfassesmenttracker',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='selfassesment_tracker_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='selfassesmenttracker',
            name='done_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selfassesment_tracker_done_by', to=settings.AUTH_USER_MODEL, verbose_name='Done By'),
        ),
        migrations.AddField(
            model_name='selfassesmenttracker',
            name='issue_created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selfassesment_tracker_issue_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Issue Created By'),
        ),
        migrations.AddField(
            model_name='autocreatedselfassesmenttracker',
            name='selfassesment_tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.selfassesmenttracker'),
        ),
        migrations.AddField(
            model_name='selfassesment',
            name='selfassesment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='selfassesment_type_id', to='companies.selfassesmenttype', verbose_name='Selfassesment Type'),
        ),
        migrations.AddField(
            model_name='selfemploymentincomeandexpensesdatacollection',
            name='selfassesment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.selfassesment'),
        ),
        migrations.AddField(
            model_name='selfemploymentincomeandexpensesdatacollection',
            name='tax_year',
            field=models.ForeignKey(default=companies.models.SelfassesmentAccountSubmissionTaxYear.get_max_year, on_delete=django.db.models.deletion.RESTRICT, to='companies.selfassesmentaccountsubmissiontaxyear'),
        ),
        migrations.AddField(
            model_name='trackerhasissues',
            name='issue_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='TrackerHasIssues_issue_id', to='companies.issue', verbose_name='Tracker Id'),
        ),
        migrations.AddField(
            model_name='trackerhasissues',
            name='tracker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TrackerHasIssues_tracker_id', to='companies.selfassesmenttracker', verbose_name='Tracker Id'),
        ),
        migrations.AddIndex(
            model_name='limitedonboardingtasks',
            index=models.Index(fields=['task_status'], name='companies_l_task_st_dc0b57_idx'),
        ),
        migrations.AddConstraint(
            model_name='limitedonboardingtasks',
            constraint=models.UniqueConstraint(fields=('client_id', 'task_id'), name='unique_client_id__task_id__limited_onboarding_tasks'),
        ),
        migrations.AddConstraint(
            model_name='selfassesmentaccountsubmission',
            constraint=models.UniqueConstraint(fields=('client_id', 'tax_year'), name='unique_client_id__tax_year__status_SUBMITTED'),
        ),
        migrations.AddConstraint(
            model_name='autocreatedselfassesmenttracker',
            constraint=models.UniqueConstraint(fields=('selfassesment', 'reference'), name='Unique issue'),
        ),
    ]
