# Generated by Django 3.1.7 on 2021-04-30 16:14

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfassesment',
            name='UTR',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid UTR', message='Enter 10 digit UTR Number', regex=re.compile('^[0-9]{10}$'))], verbose_name='UTR'),
        ),
        migrations.AlterField(
            model_name='selfassesmenttracker',
            name='complete_date',
            field=models.DateField(blank=True, null=True, verbose_name='Complete Date'),
        ),
    ]
