# Generated by Django 3.1.7 on 2021-05-06 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='selfassesmenttracker',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='selfassesment_tracker_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='selfassesmenttracker',
            name='done_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selfassesment_tracker_done_by', to=settings.AUTH_USER_MODEL, verbose_name='Done By'),
        ),
        migrations.AddField(
            model_name='selfassesmentaccountsubmission',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selfassesment_account_submission_client_id', to='companies.selfassesment', verbose_name='Client ID'),
        ),
        migrations.AddField(
            model_name='selfassesmentaccountsubmission',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selfassesment_account_submission_prepared_by', to=settings.AUTH_USER_MODEL, verbose_name='Prepared By'),
        ),
        migrations.AddField(
            model_name='selfassesmentaccountsubmission',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selfassesment_account_submission_submitted_by', to=settings.AUTH_USER_MODEL, verbose_name='Submitted By'),
        ),
        migrations.AddField(
            model_name='selfassesment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selfassesment_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='selfassesment',
            name='selfassesment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='selfassesment_type_id', to='companies.selfassesmenttype', verbose_name='Selfassesment Type'),
        ),
    ]
