# Generated by Django 5.1.4 on 2025-02-19 17:06

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limited',
            name='NINO',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(code='Invalid NINO', message='Enter 9 chars long NINO.', regex=re.compile('^(?!BG|GB|KN|NK|NT|TN|ZZ)[ABCEGHJKLMNOPRSTWXYZ][ABCEGHJKLMNPRSTWXYZ][0-9]{6}[ABCD]$', 2))], verbose_name='NINO'),
        ),
    ]
