# Generated by Django 3.1.7 on 2021-04-19 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0002_auto_20210419_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitedtracker',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='limited_tracker_created_by', to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='limitedtracker',
            name='done_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limited_tracker_done_by', to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='Done By'),
        ),
        migrations.AlterField(
            model_name='selfassesmentaccountsubmission',
            name='account_prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_prepared_by', to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='Prepared By'),
        ),
        migrations.AlterField(
            model_name='selfassesmentaccountsubmission',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.selfassesment', verbose_name='Client ID'),
        ),
        migrations.AlterField(
            model_name='selfassesmentaccountsubmission',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_by', to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='Submitted By'),
        ),
        migrations.AlterField(
            model_name='selfassesmenttracker',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selfassesment_client_id', to='companies.selfassesment', verbose_name='Client ID'),
        ),
        migrations.AlterField(
            model_name='selfassesmenttracker',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='selfassesment_tracker_created_by', to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='selfassesmenttracker',
            name='done_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selfassesment_trackerdone_by', to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='Done By'),
        ),
    ]
