# Generated by Django 3.1.7 on 2021-04-30 16:15

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20210430_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfassesment',
            name='NINO',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid NINO', message='Enter 9 chars long NINO.', regex=re.compile('^(?!BG|GB|KN|NK|NT|TN|ZZ)[ABCEGHJKLMNOPRSTWXYZ][ABCEGHJKLMNPRSTWXYZ][0-9]{6}[ABCD]$', 2))], verbose_name='NINO'),
        ),
    ]
