# Generated by Django 3.1.7 on 2021-04-19 15:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0003_auto_20210419_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='limited',
            name='HMRC_referance',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='HMRC'),
        ),
        migrations.AddField(
            model_name='limited',
            name='NINO',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(code='Invalid NINO', message='Enter 9 chars long NINO.', regex=re.compile('^(?!BG|GB|KN|NK|NT|TN|ZZ)[ABCEGHJKLMNOPRSTWXYZ][ABCEGHJKLMNPRSTWXYZ][0-9]{6}[ABCD]$', 2))], verbose_name='NINO'),
        ),
        migrations.AddField(
            model_name='limited',
            name='UTR',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='Invalid UTR', message='Enter 10 digit UTR Number', regex=re.compile('^[0-9]{10}$'))], verbose_name='UTR'),
        ),
        migrations.AddField(
            model_name='limited',
            name='address',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='limited',
            name='bank_account_holder_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bank Account Holder Name'),
        ),
        migrations.AddField(
            model_name='limited',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(code='Invalid Bank Account', message='Enter 8 digit Bank Account Number', regex=re.compile('^[0-9]{8}$'))], verbose_name='Account number in Bank'),
        ),
        migrations.AddField(
            model_name='limited',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of Bank'),
        ),
        migrations.AddField(
            model_name='limited',
            name='bank_sort_code',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(code='Invalid Sort Code', message='Enter 6 digit Sort Code', regex=re.compile('^[0-9]{6}$'))], verbose_name='Bank Sort Code'),
        ),
        migrations.AddField(
            model_name='limited',
            name='client_file_number',
            field=models.IntegerField(null=True, unique=True, verbose_name='File Number'),
        ),
        migrations.AddField(
            model_name='limited',
            name='client_name',
            field=models.CharField(db_index=True, default='not set', max_length=100, verbose_name='Full Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='limited',
            name='client_phone_number',
            field=models.CharField(db_index=True, default='not set', max_length=255, verbose_name='Phone numbers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='limited',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limited_created_by', to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='limited',
            name='date_of_registration',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Registration date'),
        ),
        migrations.AddField(
            model_name='limited',
            name='email',
            field=models.EmailField(blank=True, max_length=320, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='limited',
            name='gateway_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Gateway ID'),
        ),
        migrations.AddField(
            model_name='limited',
            name='gateway_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Gateway Password'),
        ),
        migrations.AddField(
            model_name='limited',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active Status'),
        ),
        migrations.AddField(
            model_name='limited',
            name='is_updated',
            field=models.BooleanField(default=True, editable=False, verbose_name='Update Status'),
        ),
        migrations.AddField(
            model_name='limited',
            name='post_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='limited',
            name='client_id',
            field=models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique ID for client'),
        ),
        migrations.AlterField(
            model_name='limitedtracker',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limited_tracker_client_id', to='companies.limited', verbose_name='Client ID'),
        ),
        migrations.AlterField(
            model_name='selfassesment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selfassesment_created_by', to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='selfassesmentaccountsubmission',
            name='account_prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selfassesment_account_submission_prepared_by', to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='Prepared By'),
        ),
        migrations.AlterField(
            model_name='selfassesmentaccountsubmission',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selfassesment_account_submission_client_id', to='companies.selfassesment', verbose_name='Client ID'),
        ),
        migrations.AlterField(
            model_name='selfassesmentaccountsubmission',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selfassesment_account_submission_submitted_by', to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='Submitted By'),
        ),
        migrations.AlterField(
            model_name='selfassesmenttracker',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selfassesment_tracker_client_id', to='companies.selfassesment', verbose_name='Client ID'),
        ),
        migrations.AlterField(
            model_name='selfassesmenttracker',
            name='done_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selfassesment_tracker_done_by', to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='Done By'),
        ),
        migrations.CreateModel(
            name='LimitedAccountSubmission',
            fields=[
                ('submission_id', models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False, verbose_name='Submission ID')),
                ('date_of_submission', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Submission date')),
                ('tax_year', models.CharField(blank=True, max_length=10, verbose_name='Tax Year')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('paid_amount', models.BigIntegerField(blank=True, null=True, verbose_name='Amount Paid')),
                ('is_paid', models.BooleanField(blank=True, default=False, verbose_name='Is Paid')),
                ('is_submitted', models.BooleanField(blank=True, default=False, verbose_name='Is Submitted')),
                ('account_prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='limited_account_submission_prepared_by', to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='Prepared By')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limited_account_submission_client_id', to='companies.limited', verbose_name='Client ID')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='limited_account_submission_submitted_by', to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='Submitted By')),
            ],
            options={
                'verbose_name': 'Limited Submission',
                'verbose_name_plural': 'Limited Submissions',
            },
        ),
    ]
