# Generated by Django 3.2.2 on 2021-05-21 04:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20210519_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfassesmenttracker',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.localtime, editable=False, verbose_name='Creation Datetime'),
        ),
    ]
