# Generated by Django 3.1.7 on 2021-04-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20210430_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfassesment',
            name='HMRC_referance',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='HMRC Referance'),
        ),
    ]
