# Generated by Django 3.1.7 on 2021-05-01 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20210430_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selfassesmentaccountsubmission',
            old_name='account_prepared_by',
            new_name='prepared_by',
        ),
    ]
