# Generated by Django 3.2.2 on 2021-05-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_selfassesmenttracker_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfassesment',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Date of Birth'),
        ),
    ]
