# Generated by Django 3.1.7 on 2021-05-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20210501_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='limitedaccountsubmission',
            old_name='account_prepared_by',
            new_name='prepared_by',
        ),
        migrations.AddField(
            model_name='selfassesment',
            name='HMRC_agent',
            field=models.BooleanField(default=False, verbose_name='HMRC agent active status'),
        ),
    ]
