# Generated by Django 3.1.7 on 2021-05-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20210501_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limitedaccountsubmission',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='limitedaccountsubmission',
            name='prepared_by',
        ),
        migrations.RemoveField(
            model_name='limitedaccountsubmission',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='limitedtracker',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='limitedtracker',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='limitedtracker',
            name='done_by',
        ),
        migrations.RenameField(
            model_name='selfassesment',
            old_name='address',
            new_name='business_address',
        ),
        migrations.RenameField(
            model_name='selfassesment',
            old_name='email',
            new_name='business_email',
        ),
        migrations.RemoveField(
            model_name='selfassesment',
            name='client_phone_number',
        ),
        migrations.AddField(
            model_name='selfassesment',
            name='business_phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Phone numbers'),
        ),
        migrations.AddField(
            model_name='selfassesment',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='selfassesment',
            name='personal_address',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='selfassesment',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=320, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='selfassesment',
            name='personal_phone_number',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Phone numbers'),
        ),
        migrations.DeleteModel(
            name='Limited',
        ),
        migrations.DeleteModel(
            name='LimitedAccountSubmission',
        ),
        migrations.DeleteModel(
            name='LimitedTracker',
        ),
    ]
