# Generated by Django 3.2.2 on 2021-05-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20210531_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackerhasissues',
            name='id',
            field=models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Issue Id'),
        ),
    ]
