# Generated by Django 3.2.2 on 2021-06-04 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0007_alter_trackerhasissues_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfassesmenttracker',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='selfassesment_tracker_assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to'),
        ),
        migrations.AddField(
            model_name='selfassesmenttracker',
            name='new_customer',
            field=models.BooleanField(blank=True, default=False, editable=False, null=True, verbose_name='New customer'),
        ),
    ]
