# Generated by Django 3.1.7 on 2021-05-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_auto_20210501_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfassesmentType',
            fields=[
                ('type_id', models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Selfassesment Type Id')),
                ('type_name', models.CharField(db_index=True, default='New Type', max_length=255, verbose_name='Type Name')),
            ],
            options={
                'verbose_name': 'Selfassesment Type',
                'verbose_name_plural': 'Selfassesment Types',
            },
        ),
        migrations.AlterField(
            model_name='selfassesment',
            name='personal_address',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='Personal Address'),
        ),
        migrations.AlterField(
            model_name='selfassesment',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=320, null=True, verbose_name='Personal Email'),
        ),
        migrations.AlterField(
            model_name='selfassesment',
            name='personal_phone_number',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Personal Phone numbers'),
        ),
    ]
