# Generated by Django 3.2.2 on 2021-06-26 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_auto_20210626_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='limited',
            name='vat',
            field=models.CharField(blank=True, max_length=255, verbose_name='VAT'),
        ),
    ]
