# Generated by Django 3.1.7 on 2021-05-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_selfassesment_selfassesment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selfassesment',
            old_name='post_code',
            new_name='business_post_code',
        ),
        migrations.AddField(
            model_name='selfassesment',
            name='personal_post_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Personal Postal Code'),
        ),
        migrations.AlterField(
            model_name='selfassesment',
            name='HMRC_referance',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='HMRC Referance'),
        ),
        migrations.AlterField(
            model_name='selfassesment',
            name='business_address',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='Business Address'),
        ),
        migrations.AlterField(
            model_name='selfassesment',
            name='business_email',
            field=models.EmailField(blank=True, max_length=320, null=True, verbose_name='Business Email'),
        ),
        migrations.AlterField(
            model_name='selfassesment',
            name='business_phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Business Phone numbers'),
        ),
        migrations.AlterField(
            model_name='selfassesmenttype',
            name='type_name',
            field=models.CharField(db_index=True, default='New Selfassesment Type', max_length=255, verbose_name='Type Name'),
        ),
    ]
