# Generated by Django 3.1.7 on 2021-05-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_auto_20210501_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfassesment',
            name='AOR_number',
            field=models.CharField(db_index=True, max_length=511, null=True, verbose_name='Account Office Reference number'),
        ),
        migrations.AddField(
            model_name='selfassesment',
            name='PAYE_number',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='PAYE Number'),
        ),
        migrations.AddField(
            model_name='selfassesment',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks'),
        ),
    ]
