# Generated by Django 3.2.2 on 2021-06-27 07:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_limited_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='limited',
            name='company_auth_code',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='Company Authentication Code'),
        ),
        migrations.AddField(
            model_name='limited',
            name='company_reg_number',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='Company Registration Number'),
        ),
        migrations.AlterField(
            model_name='limited',
            name='bank_account_holder_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Account Holder Name'),
        ),
        migrations.AlterField(
            model_name='limited',
            name='client_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Business Name'),
        ),
        migrations.AlterField(
            model_name='limited',
            name='date_of_registration',
            field=models.DateField(default=django.utils.timezone.localtime, null=True, verbose_name='Registration date'),
        ),
        migrations.AlterField(
            model_name='limited',
            name='vat',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='VAT'),
        ),
        migrations.AlterField(
            model_name='selfassesment',
            name='bank_account_holder_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Account Holder Name'),
        ),
        migrations.AlterField(
            model_name='selfassesmentaccountsubmission',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selfassesment_account_submission_client_id', to='companies.selfassesment', verbose_name='Client ID'),
        ),
        migrations.AlterField(
            model_name='selfassesmenttracker',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selfassesment_tracker_client_id', to='companies.selfassesment', verbose_name='Client ID'),
        ),
        migrations.AlterField(
            model_name='selfassesmenttracker',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.localtime, editable=False, null=True, verbose_name='Creation Datetime'),
        ),
        migrations.AlterField(
            model_name='selfassesmenttracker',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.localtime, null=True, verbose_name='Deadline'),
        ),
    ]
