# Generated by Django 3.2.2 on 2021-06-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_auto_20210627_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limited',
            name='client_file_number',
            field=models.DecimalField(decimal_places=3, max_digits=19, null=True, unique=True, verbose_name='File Number'),
        ),
    ]
