# Generated by Django 3.1.7 on 2021-05-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_auto_20210502_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfassesment',
            name='AOR_number',
            field=models.CharField(blank=True, db_index=True, max_length=511, null=True, verbose_name='Account Office Reference number'),
        ),
        migrations.AlterField(
            model_name='selfassesment',
            name='PAYE_number',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='PAYE Number'),
        ),
        migrations.AlterField(
            model_name='selfassesment',
            name='business_post_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Business Postal Code'),
        ),
        migrations.AlterField(
            model_name='selfassesment',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
    ]
