# Generated by Django 3.1.7 on 2021-05-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_auto_20210505_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfassesment',
            name='PAYE_number',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='PAYE Number'),
        ),
        migrations.AlterField(
            model_name='selfassesment',
            name='gateway_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Personal Gateway ID'),
        ),
    ]
