# Generated by Django 3.2.2 on 2021-06-28 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0013_limitedtracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limited',
            name='date_of_registration',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Registration date'),
        ),
        migrations.AlterField(
            model_name='limitedtracker',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True, verbose_name='Creation Datetime'),
        ),
        migrations.AlterField(
            model_name='limitedtracker',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='selfassesment',
            name='date_of_registration',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Registration date'),
        ),
        migrations.AlterField(
            model_name='selfassesmentaccountsubmission',
            name='date_of_submission',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Submission date'),
        ),
        migrations.AlterField(
            model_name='selfassesmenttracker',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True, verbose_name='Creation Datetime'),
        ),
        migrations.AlterField(
            model_name='selfassesmenttracker',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Deadline'),
        ),
        migrations.CreateModel(
            name='LimitedSubmissionDeadlineTracker',
            fields=[
                ('submission_id', models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False, verbose_name='Submission ID')),
                ('period', models.CharField(blank=True, default='', max_length=63, null=True, verbose_name='Period')),
                ('our_deadline', models.DateField(blank=True, null=True, verbose_name='Our Deadline')),
                ('HMRC_deadline', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Registration date')),
                ('is_submitted', models.BooleanField(default=False, verbose_name='Is Submitted')),
                ('submitted_by', models.TextField(blank=True, default='', verbose_name='Submitted By')),
                ('submission_date', models.DateField(blank=True, verbose_name='Submission Date')),
                ('is_documents_uploaded', models.BooleanField(default=False, verbose_name='Is Documents Uploaded')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('last_updated_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Updated On')),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selfassesment_account_submission_client_id', to='companies.limited', verbose_name='Client ID')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='limited_submission_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Limited Submission',
                'verbose_name_plural': 'Limited Submissions',
            },
        ),
    ]
