# Generated by Django 3.2.2 on 2021-06-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_auto_20210628_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitedsubmissiondeadlinetracker',
            name='HMRC_deadline',
            field=models.DateField(null=True, verbose_name='Registration date'),
        ),
    ]
