# Generated by Django 3.2.2 on 2021-06-28 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_alter_limitedsubmissiondeadlinetracker_hmrc_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitedsubmissiondeadlinetracker',
            name='HMRC_deadline',
            field=models.DateField(null=True, verbose_name='HMRC Deadline'),
        ),
    ]
