# Generated by Django 3.2.2 on 2021-06-28 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_alter_limitedsubmissiondeadlinetracker_hmrc_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitedsubmissiondeadlinetracker',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='limited_account_submission_client_id', to='companies.limited', verbose_name='Client ID'),
        ),
        migrations.AlterField(
            model_name='limitedsubmissiondeadlinetracker',
            name='is_documents_uploaded',
            field=models.BooleanField(default=False, verbose_name='Is Documents Uploaded'),
        ),
        migrations.AlterField(
            model_name='limitedsubmissiondeadlinetracker',
            name='is_submitted',
            field=models.BooleanField(default=False, verbose_name='Is Submitted'),
        ),
    ]
