# Generated by Django 3.2.2 on 2021-06-28 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0018_auto_20210628_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitedsubmissiondeadlinetracker',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='limited_submission_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By'),
        ),
    ]
