# Generated by Django 3.2.2 on 2021-07-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0019_alter_limitedsubmissiondeadlinetracker_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='limited',
            name='director_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Director Name'),
        ),
    ]
