# Generated by Django 3.2.2 on 2021-07-17 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0020_limited_director_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitedVATTracker',
            fields=[
                ('vat_id', models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False, verbose_name='Submission ID')),
                ('period_start', models.DateTimeField(blank=True, null=True, verbose_name='Period Start')),
                ('period_end', models.DateTimeField(blank=True, null=True, verbose_name='Period End')),
                ('HMRC_deadline', models.DateField(null=True, verbose_name='HMRC Deadline')),
                ('is_submitted', models.BooleanField(default=False, verbose_name='Is Submitted')),
                ('submitted_by', models.TextField(blank=True, default='', null=True, verbose_name='Submitted By')),
                ('submission_date', models.DateField(blank=True, null=True, verbose_name='Submission Date')),
                ('is_documents_uploaded', models.BooleanField(default=False, verbose_name='Is Documents Uploaded')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('last_updated_on', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Last Updated On')),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='limited_vat_client_id', to='companies.limited', verbose_name='Client ID')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='limited_vat_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
            ],
            options={
                'verbose_name': 'Limited VAT Tracker',
                'verbose_name_plural': 'Limited VAT Trackers',
            },
        ),
    ]
