# Generated by Django 3.2.2 on 2021-07-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0021_limitedvattracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitedvattracker',
            name='period_end',
            field=models.DateField(blank=True, null=True, verbose_name='Period End'),
        ),
        migrations.AlterField(
            model_name='limitedvattracker',
            name='period_start',
            field=models.DateField(blank=True, null=True, verbose_name='Period Start'),
        ),
        migrations.AlterField(
            model_name='limitedvattracker',
            name='vat_id',
            field=models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False, verbose_name='VAT Tracker ID'),
        ),
    ]
