# Generated by Django 3.2.2 on 2021-07-23 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0023_auto_20210720_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfassesmentAccountSubmissionTaxYear',
            fields=[
                ('id', models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False, verbose_name='Tax Year ID')),
                ('tax_year', models.CharField(max_length=12, verbose_name='Selfassesment Account Submission Tax Year')),
            ],
            options={
                'verbose_name': 'Selfassesment Tax Year',
                'verbose_name_plural': 'Selfassesment Tax Years',
            },
        ),
        migrations.AlterField(
            model_name='selfassesmentaccountsubmission',
            name='tax_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='companies.selfassesmentaccountsubmissiontaxyear'),
        ),
    ]
