# Generated by Django 3.2.2 on 2021-07-23 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0024_auto_20210723_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfassesmentaccountsubmission',
            name='tax_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='companies.selfassesmentaccountsubmissiontaxyear'),
        ),
    ]
