# Generated by Django 3.2.2 on 2021-07-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0025_alter_selfassesmentaccountsubmission_tax_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selfassesmentaccountsubmission',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='selfassesmentaccountsubmission',
            name='payment_status',
            field=models.CharField(choices=[('N', 'NOT PAID'), ('P', 'PARTIALLY PAID'), ('Y', 'PAID')], default='N', max_length=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='selfassesmentaccountsubmission',
            name='status',
            field=models.CharField(choices=[('PC', 'PROCESSING'), ('BA', 'BOOK APPOINTMENT'), ('RS', 'READY FOR SUBMIT'), ('WC', 'WAITING FOR CONFIRMAITION'), ('SB', 'SUBMITTED')], default='PR', max_length=24, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='selfassesmentaccountsubmissiontaxyear',
            name='tax_year',
            field=models.CharField(max_length=12, verbose_name='Tax Year'),
        ),
    ]
