# Generated by Django 3.2.2 on 2021-07-23 23:03

import companies.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0026_auto_20210724_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfassesmentaccountsubmission',
            name='payment_status',
            field=models.CharField(choices=[('NOT PAID', 'NOT PAID'), ('PARTIALLY PAID', 'PARTIALLY PAID'), ('PAID', 'PAID')], default='N', max_length=55, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='selfassesmentaccountsubmission',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'PROCESSING'), ('BOOK APPOINTMENT', 'BOOK APPOINTMENT'), ('READY FOR SUBMIT', 'READY FOR SUBMIT'), ('WAITING FOR CONFIRMAITION', 'WAITING FOR CONFIRMAITION'), ('SUBMITTED', 'SUBMITTED')], default='PR', max_length=55, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='selfassesmentaccountsubmission',
            name='tax_year',
            field=models.ForeignKey(default=companies.models.SelfassesmentAccountSubmissionTaxYear.get_max_year, null=True, on_delete=django.db.models.deletion.RESTRICT, to='companies.selfassesmentaccountsubmissiontaxyear'),
        ),
    ]
