# Generated by Django 3.2.2 on 2021-07-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0027_auto_20210724_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfassesmentaccountsubmission',
            name='payment_status',
            field=models.CharField(choices=[('NOT PAID', 'NOT PAID'), ('PARTIALLY PAID', 'PARTIALLY PAID'), ('PAID', 'PAID')], default='NOT PAID', max_length=55, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='selfassesmentaccountsubmission',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'PROCESSING'), ('BOOK APPOINTMENT', 'BOOK APPOINTMENT'), ('READY FOR SUBMIT', 'READY FOR SUBMIT'), ('WAITING FOR CONFIRMAITION', 'WAITING FOR CONFIRMAITION'), ('SUBMITTED', 'SUBMITTED')], default='PROCESSING', max_length=55, verbose_name='Status'),
        ),
    ]
