# Generated by Django 3.2.2 on 2021-07-24 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0028_auto_20210724_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfassesmentaccountsubmission',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='selfassesment_account_submission_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By'),
        ),
        migrations.AddField(
            model_name='selfassesmentaccountsubmission',
            name='last_updated_on',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Last Updated On'),
        ),
    ]
