# Generated by Django 3.2.2 on 2021-07-24 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0029_auto_20210724_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfassesmentaccountsubmission',
            name='appointment_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Appointment Date'),
        ),
        migrations.AddField(
            model_name='selfassesmentaccountsubmission',
            name='request_date',
            field=models.DateField(null=True, verbose_name='Request Date'),
        ),
        migrations.AlterField(
            model_name='selfassesmentaccountsubmission',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
        migrations.AlterUniqueTogether(
            name='selfassesmentaccountsubmission',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='selfassesmentaccountsubmission',
            name='date_of_submission',
        ),
    ]
