# Generated by Django 3.2.2 on 2021-07-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0030_auto_20210724_1506'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='selfassesmentaccountsubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'SUBMITTED')), fields=('client_id', 'tax_year'), name='unique_client_id__tax_year__status_SUBMITTED'),
        ),
    ]
